Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end


  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/docker-ce.yml"
      ansible.groups = {
      "app" => ["appserver"],
      "app:vars" => { "db_host" => "10.10.10.10"}
      }      
    end
  end
end
