# vars for gitlab-runners
no_log: False
gitlab_runner_registration_token: 'KxzDNYZ4FZmtc8feHxsC'
gitlab_runner_coordinator_url: "http://35.202.29.119/"
gitlab_runner_package_name: gitlab-runner
gitlab_runner_runners:
  - name: "Privileged docker runner"
    executor: docker
    docker_image: "docker:19.03"
    tags:
      - docker
      - linux
      - dind
    docker_volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/cache"
    docker_privileged: true
